#!/bin/sh

# Start of note
# 
#
#
#
#
#
#
#
#
#
#
#
#
# End of note

# Build values
tmp=".tmp/"
# Colors
cclr="\e[0m"
cred="\e[91m"
cylw="\e[93m"
cgrn="\e[92m"
cbl="\e[94m"
ccn="\e[96m"
cmgt="\e[95m"
cgr="\e[90m"

lcolors=(red yellow green aqua blue light_purple white gray)
dcolors=(dark_red gold dark_green dark_aqua dark_blue dark_purple black dark_gray)

# Assets paths
textures_path="textures/"
icons_path="icons/"

# Zip paths
icon_path="pack.png"
meta_path="pack.mcmeta"
texture_path="assets/minecraft/textures/item/"
lang_path="assets/minecraft/lang/"

# Functions

new_config () {
printf "pack:version : ${cylw}"; read version; printf "${cclr}"
echo "version=$version" > .latest_tb

printf "pack:description:name : ${cylw}"; read name; printf "${cclr}"
echo "name=$name" >> .latest_tb

printf "pack:description:name:color : "; echo
select ctype in "l" "d"; do
	if [[ $ctype == "l" ]]; then
	select color in "${lcolors[@]}"; do
		break
	done; break
elif [[ $ctype == "d" ]]; then
	select color in "${dcolors[@]}"; do
		break	
	done; break
else
	echo "wrong color type";
	break
fi
done
echo "color=$color" >> .latest_tb

touch $tmp".tmp"
echo "textures=(" > $tmp".tmp"
dir $textures_path >> $tmp".tmp"
echo ")" >> $tmp".tmp"

source "./$tmp.tmp"
rm $tmp".tmp"

select texture in "${textures[@]}"; do
	echo "texture=$texture" >> .latest_tb
		break
	done; break

cat .latest_tb
}

load_config () {
source ./.latest_tb
}

create_meta () {
echo "{
 \"pack\": {
  \"pack_format\": 34,
  \"description\": [{\"text\":\"$name of Undying\",\"color\":\"$color\"},{\"text\":\"\nby Ami Amai\",\color\":\"gray\"}]
  }
}" > $tmp$meta_path
}

create_lang () {
mkdir -p $tmp$lang_path
echo "{
 \"item.minecraft.totem_of_undying\": \"$name of Undying\" 
}" > $tmp$lang_path"en_us.json"
}

# Script

# Get Values for resourcepack

mkdir $tmp

echo "Do u want to laod latest config?"
select load in "Yes" "No" "Exit"; do
	if [[ $load == "Yes" ]]; then
		load_config
	elif [[ $load == "No" ]]; then
		new_config
	else
		exit
	fi
	break
done

# pack.mcmeta
create_meta

# assets/minecraft/lang/en_us.json

create_lang

# pack.png
cp -r $icons_path$texture $tmp$icon_path

# assets/minecraft/textures/item/totem_of_undying.png
mkdir -p $tmp$texture_path
cp -r $textures_path$texture $tmp$texture_path"totem_of_undying.png"

echo " $load $version $name $texture"
dir $tmp
dir $tmp$texture_path

cd $tmp
pack="$name-of-Undying_${version}_1.21.zip"
zip -0 -r -m $pack "assets/" $meta_path $icon_path
cd ..

cp $tmp$pack "resourcepacks/$pack"




